name: Nightly updates for TDLib

on:
  workflow_dispatch:
  schedule:
    - cron: "33 3 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: nightly
          submodules: recursive
      - name: Check for updates
        run: |
          cd td
          git status
          git fetch
          git reset --hard origin/master
          git status
          cd ..
          git config --local user.name "oott123"
          git config --local user.email "oott123@users.noreply.github.com"
          (git commit -am "chore: Bump TDLib version" && git push -u origin nightly) || true
