name: Nightly updates for TDLib

on:
  - workflow_dispatch:
  - schedule:
      cron: "33 3 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: nightly
          submodules: recursive
      - name: Check for updates
        run: |
          cd td && git pull
          git config --local user.name "oott123"
          git config --local user.email "oott123@users.noreply.github.com"
          git commit -m "chore: Bump TDLib version"
          git push -u origin nightly
        continue-on-error: true
